trigger: none

pool:
  name: AgentVK

variables:
  config_path: '$(System.DefaultWorkingDirectory)'
  backend_svc: 'vk-secret'

stages:

# ================= STAGE 1 =================
- stage: Validate
  displayName: "Terraform Validate Stage"
  jobs:
  - job: Validate
    displayName: "Init + Fmt + Validate"
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: init
        workingDirectory: $(config_path)
        backendServiceArm: $(backend_svc)
        backendAzureRmResourceGroupName: rg-terraform-state
        backendAzureRmStorageAccountName: stgformstate231023
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: tfstate-file

    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: custom
        customCommand: fmt
        workingDirectory: $(config_path)

    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: $(config_path)

# ================= STAGE 2 =================
- stage: Plan
  displayName: "Terraform Plan Stage"
  dependsOn: Validate
  jobs:
  - job: Plan
    displayName: "Terraform Plan"
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: init
        workingDirectory: $(config_path)
        backendServiceArm: $(backend_svc)
        backendAzureRmResourceGroupName: rg-terraform-state
        backendAzureRmStorageAccountName: stgformstate231023
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: tfstate-file

    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: $(config_path)
        environmentServiceNameAzureRM: $(backend_svc)

# ================= STAGE 3 =================
- stage: Apply
  displayName: "Terraform Apply Stage"
  dependsOn: Plan
  jobs:

  - job: ManualApproval
    displayName: "Manual Approval"
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: |
          Review Terraform plan.
          Approve to apply infrastructure changes.
        timeoutInMinutes: 1440
        onTimeout: reject

  - job: Apply
    displayName: "Terraform Apply"
    dependsOn: ManualApproval
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: init
        workingDirectory: $(config_path)
        backendServiceArm: $(backend_svc)
        backendAzureRmResourceGroupName: rg-terraform-state
        backendAzureRmStorageAccountName: stgformstate231023
        backendAzureRmContainerName: tfstate
        backendAzureRmKey: tfstate-file

    - task: TerraformTask@5
      inputs:
        provider: azurerm
        command: apply
        workingDirectory: $(config_path)
        environmentServiceNameAzureRM: $(backend_svc)

