trigger: none

parameters:
- name: runScanning
  type: boolean
  default: true

variables: 
  WorkingDir: $(System.DefaultWorkingDirectory)
  VkScerte : vk-secret

pool: AgentVK

stages:
  - stage: Build_Stage
    displayName: Buld Stage
    jobs:
    - job: 
      displayName: Terraform Init and plan job
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'

